### ISSUE TITLE
 Make the asked question section as the design

### ISSUE THREAD

**Issue by lauraalvarezzz1** [hackeo1/yeoman-project#4]
1. Make the icons keep next to the text
2. Keep a padding to the right and left, more or less than 20px
3. Keep a greater space between texts (titles no paragraphs), it can be: maybe line-height 1.5px

**Comment by hackeo1** [comment]
parent = font-size: 0;
icon =
font-size: 2rem;
width: 45px;
title = 
font-size: 1.3rem;
width: calc(100% - 45px);
display: inline-block;
margin-left: 0;
padding-left: 1rem;
